import {randomUUID}from'node:crypto';import{readFile}from'node:fs/promises';import{fileURLToPath}from'node:url';import{PGlite,type Results,type Transaction}from'@electric-sql/pglite';import type{PoolClient}from'pg';import{describe,expect,it}from'vitest';
import{PostgresCreditLedgerStore}from'../src/credits/store.js';import{KAI_CREDIT_PLATFORM_ACCOUNTS}from'../src/credits/types.js';import type{Database}from'../src/database.js';import{PostgresDeviceCommerceStore}from'../src/device-commerce/store.js';import{SPARK_PRODUCT_ID}from'../src/device-commerce/types.js';import{PostgresCreditPayoutStore}from'../src/payouts/store.js';
function result<T>(r:Results<T>){return{...r,rowCount:r.rows.length||r.affectedRows||0,command:'',oid:0,rowAsArray:false}}function adapter(p:PGlite):Database{return{health:async()=>true,schemaReadiness:async()=>({ready:true,expected:null,applied:null,missing:[],mismatched:[]}),query:async<Row extends Record<string,unknown>>(t:string,v?:unknown[])=>result(await p.query<Row>(t,v)),transaction:async<T>(w:(c:PoolClient)=>Promise<T>)=>p.transaction(async(tx:Transaction)=>w({query:async(t:string,v?:unknown[])=>result(await tx.query(t,v))}as unknown as PoolClient)),close:()=>p.close()}as unknown as Database}
async function fixture(){const p=new PGlite();for(const n of['0001_cloudpay_ledger.sql','0016_trading_subjects.sql','0022_kai_credit_double_entry_ledger.sql','0046_kai_credit_supplier_payouts.sql','0047_physical_device_commerce.sql','0048_shipping_addresses.sql','0049_supplier_earnings_accounts.sql'])await p.exec(await readFile(fileURLToPath(new URL(`../migrations/${n}`,import.meta.url)),'utf8'));const db=adapter(p);
 const buyerUser=randomUUID(),supplierUser=randomUUID(),operator=randomUUID(),buyer=randomUUID(),supplier=randomUUID();await db.query(`INSERT INTO users(id,phone_ciphertext,display_name,role)VALUES($1,'device-buyer','买方','member'),($2,'device-supplier','白鸽','supplier'),($3,'device-operator','运营','operator')`,[buyerUser,supplierUser,operator]);await db.query(`INSERT INTO trading_subjects(id,kind,display_name,owner_user_id)VALUES($1,'personal','买方',$2),($3,'organization','白鸽在线',$4)`,[buyer,buyerUser,supplier,supplierUser]);
 await db.query(`INSERT INTO shipping_addresses(id,reference,subject_id,created_by_user_id,client_request_id,payload_ciphertext,payload_digest,is_default)VALUES($1,'address-token-shanghai-001',$2,$3,'device-fixture-address-0001','encrypted-address-test',$4,true)`,[randomUUID(),buyer,buyerUser,`sha256:${'8'.repeat(64)}`]);
 const ledger=new PostgresCreditLedgerStore(db),a=await ledger.ensureSubjectAccounts(buyer);await ledger.ensureSubjectAccounts(supplier);const available=a.find(x=>x.kind==='available')!.accountId;await ledger.post({id:randomUUID(),idempotencyOwner:`subject:${buyer}`,scope:'DEVICE_TEST_SEED',idempotencyKey:`device-seed-${randomUUID()}`,payloadDigest:`sha256:${'a'.repeat(64)}`,referenceType:'topup',description:'设备测试卡时',entries:[{accountId:available,amountMicros:100_000_000_000n,memo:'充值'},{accountId:KAI_CREDIT_PLATFORM_ACCOUNTS.issuance,amountMicros:-100_000_000_000n,memo:'发行'}]});
 const payouts=new PostgresCreditPayoutStore(db);await payouts.activateProfile({subjectId:supplier,operatorId:operator,legalEntityDigest:`sha256:${'b'.repeat(64)}`,recipientReference:'white-pigeon-bank-token',now:new Date()});const store=new PostgresDeviceCommerceStore(db);await store.activateProduct(SPARK_PRODUCT_ID,supplier,operator,new Date());return{db,store,ledger,buyerUser,supplierUser,operator,buyer,supplier};}
function create(buyer:string,user:string,quantity=1){return{id:randomUUID(),orderNumber:`KDO${randomUUID().replaceAll('-','').slice(0,20)}`,buyerSubjectId:buyer,userId:user,productId:SPARK_PRODUCT_ID,quantity,shippingAddressReference:'address-token-shanghai-001',clientRequestId:`device-order-${randomUUID()}`,payloadDigest:`sha256:${randomUUID().replaceAll('-','').padEnd(64,'c').slice(0,64)}`,expiresAt:new Date(Date.now()+1_800_000),now:new Date()};}
function action(orderId:string,actorId:string,actorSubjectId:string,side:'buyer'|'supplier',data:Partial<Parameters<PostgresDeviceCommerceStore['action']>[0]>){return{orderId,actorId,actorSubjectId,side,clientRequestId:`device-action-${randomUUID()}`,payloadDigest:`sha256:${randomUUID().replaceAll('-','').padEnd(64,'d').slice(0,64)}`,now:new Date(),...data}as Parameters<PostgresDeviceCommerceStore['action']>[0]}
describe('physical NVIDIA DGX Spark commerce',()=>{
 it('keeps the seeded 200-unit product fail-closed until supplier activation',async()=>{const p=new PGlite();for(const n of['0001_cloudpay_ledger.sql','0016_trading_subjects.sql','0022_kai_credit_double_entry_ledger.sql','0046_kai_credit_supplier_payouts.sql','0047_physical_device_commerce.sql','0048_shipping_addresses.sql','0049_supplier_earnings_accounts.sql'])await p.exec(await readFile(fileURLToPath(new URL(`../migrations/${n}`,import.meta.url)),'utf8'));const db=adapter(p),store=new PostgresDeviceCommerceStore(db);expect(await store.getProduct(SPARK_PRODUCT_ID)).toMatchObject({title:'NVIDIA DGX Spark',supplierDisplayName:'白鸽在线',activationStatus:'pending_activation',inventoryTotal:200,inventoryReserved:0,inventorySold:0,listPriceCnyMicros:40_750_000_000n,salePriceCnyMicros:32_600_000_000n,discountBasisPoints:8000,expectedShipDays:90});await db.close();});
 it('atomically reserves inventory and credits, captures with tier fee, and creates buyer asset on receipt',{timeout:30_000},async()=>{const{db,store,ledger,buyerUser,supplierUser,buyer,supplier}=await fixture();const input=create(buyer,buyerUser);const made=await store.create(input);expect(made).toMatchObject({status:'created',order:{status:'reserved',grossCreditMicros:32_534_930_140n}});if(!('order'in made))throw new Error('missing order');expect(await store.getProduct(SPARK_PRODUCT_ID)).toMatchObject({inventoryReserved:1,inventorySold:0});
  const confirm=action(made.order.id,supplierUser,supplier,'supplier',{action:'confirm',from:'reserved',to:'confirmed'});expect(await store.action(confirm)).toMatchObject({status:'updated',order:{status:'confirmed'}});expect(await store.action(confirm)).toMatchObject({status:'replayed',order:{status:'confirmed'}});
  expect(await store.action(action(made.order.id,supplierUser,supplier,'supplier',{action:'ship',from:'confirmed',to:'shipping',logisticsProvider:'顺丰',trackingDigest:`sha256:${'e'.repeat(64)}`}))).toMatchObject({status:'updated',order:{status:'shipping'}});
  const received=await store.action(action(made.order.id,buyerUser,buyer,'buyer',{action:'receive',from:'shipping',to:'received'}));expect(received).toMatchObject({status:'updated',order:{status:'received',serviceFeeCreditMicros:325_349_302n,supplierNetCreditMicros:32_209_580_838n}});expect(await store.getProduct(SPARK_PRODUCT_ID)).toMatchObject({inventoryReserved:0,inventorySold:1});expect(await store.listAssets(buyer)).toMatchObject([{title:'NVIDIA DGX Spark',quantity:1,status:'owned'}]);
  let b=await ledger.ensureSubjectAccounts(buyer),s=await ledger.ensureSubjectAccounts(supplier);expect(b.find(x=>x.kind==='reserved')?.amountMicros).toBe(0n);expect(s.find(x=>x.kind==='supplier_receivable')?.amountMicros).toBe(32_209_580_838n);expect(s.find(x=>x.kind==='available')?.amountMicros).toBe(0n);
  expect(await store.settle({orderId:made.order.id,actorId:supplierUser,actorSubjectId:supplier,clientRequestId:`device-settle-${randomUUID()}`,payloadDigest:`sha256:${'f'.repeat(64)}`,now:new Date()})).toMatchObject({status:'not_due'});
  const settlementInput={orderId:made.order.id,actorId:supplierUser,actorSubjectId:supplier,clientRequestId:`device-settle-${randomUUID()}`,payloadDigest:`sha256:${'1'.repeat(64)}`,now:new Date(Date.now()+8*24*60*60*1000)};expect(await store.settle(settlementInput)).toMatchObject({status:'updated',settlement:{status:'succeeded',netCreditMicros:32_209_580_838n}});expect(await store.settle(settlementInput)).toMatchObject({status:'replayed',settlement:{status:'succeeded'}});
  s=await ledger.ensureSubjectAccounts(supplier);expect(s.find(x=>x.kind==='supplier_receivable')?.amountMicros).toBe(0n);expect(s.find(x=>x.kind==='available')?.amountMicros).toBe(0n);expect(s.find(x=>x.kind==='supplier_earnings_available')?.amountMicros).toBe(32_209_580_838n);const revenue=await db.query<{amount:string}>(`SELECT COALESCE(sum(e.amount_micros),0)::text amount FROM kai_credit_entries e JOIN kai_credit_transactions t ON t.id=e.transaction_id WHERE e.account_id=$1 AND t.status='posted'`,[KAI_CREDIT_PLATFORM_ACCOUNTS.revenue]);expect(BigInt(revenue.rows[0]!.amount)).toBe(325_349_302n);await db.close();});
 it('returns stock and credits on cancellation or expiry and allows only affordable competing purchases',{timeout:30_000},async()=>{const{db,store,ledger,buyerUser,buyer}=await fixture();const attempts=await Promise.all([store.create(create(buyer,buyerUser,2)),store.create(create(buyer,buyerUser,2))]);expect(attempts.map(x=>x.status).sort()).toEqual(['created','insufficient_credits']);const made=attempts.find(x=>'order'in x);if(!made||!('order'in made))throw new Error('missing order');expect(await store.action(action(made.order.id,buyerUser,buyer,'buyer',{action:'cancel',from:'reserved',to:'cancelled'}))).toMatchObject({status:'updated',order:{status:'cancelled'}});
  const expiredInput={...create(buyer,buyerUser,1),expiresAt:new Date(Date.now()-1000)};expect(await store.create(expiredInput)).toMatchObject({status:'created',order:{status:'reserved'}});expect(await store.expireReservations(new Date(),100)).toBe(1);expect(await store.getProduct(SPARK_PRODUCT_ID)).toMatchObject({inventoryReserved:0,inventorySold:0});expect((await ledger.ensureSubjectAccounts(buyer)).find(x=>x.kind==='available')?.amountMicros).toBe(100_000_000_000n);
  await db.query(`UPDATE shipping_addresses SET status='deleted',deleted_at=now(),is_default=false WHERE subject_id=$1`,[buyer]);expect(await store.create(create(buyer,buyerUser,1))).toEqual({status:'address_unavailable'});expect(await store.getProduct(SPARK_PRODUCT_ID)).toMatchObject({inventoryReserved:0,inventorySold:0});await db.close();});
});
