import { randomBytes, randomUUID } from 'node:crypto';
import { spawn, spawnSync, type ChildProcess } from 'node:child_process';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

const secret=()=>randomBytes(32).toString('base64url');
const env={...process.env,NODE_ENV:'test' as const,LOCAL_E2E:'true',PORT:'4197',STAGING_DATABASE_PATH:'memory://',
  STAGING_BUYER_TOKEN:secret(),STAGING_CREATOR_TOKEN:secret(),STAGING_OPERATOR_ACCESS_TOKEN:secret(),
  STAGING_SUPPLIER_TOKEN:secret(),STAGING_OPERATOR_CONTROL_TOKEN:secret()};
let child:ChildProcess;
let databaseRoot='';
const base='http://127.0.0.1:4197';
const headers=(token=env.STAGING_BUYER_TOKEN!)=>({'x-zod-client-environment':'staging','x-kai-e2e-session':token});
const operatorHeaders=()=>({...headers(env.STAGING_OPERATOR_ACCESS_TOKEN!),'x-zod-staging-operator-token':env.STAGING_OPERATOR_CONTROL_TOKEN!});
const sshString=(value:Buffer|string)=>{const bytes=Buffer.isBuffer(value)?value:Buffer.from(value);const length=Buffer.alloc(4);length.writeUInt32BE(bytes.length);return Buffer.concat([length,bytes]);};
const sshPublicKey=()=>{const blob=Buffer.concat([sshString('ssh-ed25519'),sshString(Buffer.alloc(32,9))]);return`ssh-ed25519 ${blob.toString('base64')} discarded-comment`;};
const supplierDraft=(clientDraftId=randomUUID())=>({clientDraftId,resource:{name:'H100 测试资源',gpuModel:'H100',gpuCardType:'SXM',gpuCount:8,gpuMemoryGb:80,regionCode:'CN-SH',city:'上海',machineType:'bare_metal',cpuModel:'Xeon Platinum',cpuCores:96,memoryGb:2048,storageGb:7000,networkMbps:10000,operatingSystem:'ubuntu_22_04',capacityGpuHours:'1000.00',fulfillmentNotes:'按约定可用时间段准备资源。'},deliveryPlan:{mode:'scheduled_window',startsAt:'2026-09-01T00:00:00.000Z',endsAt:'2026-10-01T00:00:00.000Z',timezone:'Asia/Shanghai',leadTimeHours:null},pricing:{unit:'KAI_CARD_HOUR_PER_GPU_HOUR',amount:'10.00'},acknowledgements:{ownershipConfirmed:true,remoteAccessSafetyAcknowledged:true}});

async function waitReady(){for(let attempt=0;attempt<300;attempt+=1){try{const response=await fetch(`${base}/mobile/v1/staging/health`,{headers:headers()});if(response.ok)return;}catch{}await new Promise(resolve=>setTimeout(resolve,50));}throw new Error('sandbox did not start');}
async function startServer(){child=spawn(process.execPath,['--import','tsx','staging-sandbox/server.ts'],{cwd:new URL('..',import.meta.url),env,stdio:'ignore'});await waitReady();}
async function stopServer(){if(child.exitCode!==null)return;child.kill('SIGTERM');await new Promise(resolve=>child.once('exit',resolve));}

describe('staging sandbox HTTP isolation contract',()=>{
  beforeAll(async()=>{databaseRoot=await mkdtemp(join(tmpdir(),'zod-staging-sandbox-http-'));env.STAGING_DATABASE_PATH=join(databaseRoot,'zod-staging-sandbox');await startServer();},30_000);
  afterAll(async()=>{await stopServer();await rm(databaseRoot,{recursive:true,force:true});});

  it('marks every response and rejects environment/auth scheme mismatches',async()=>{const response=await fetch(`${base}/mobile/v1/staging/balance`,{headers:headers()});expect(response.status).toBe(200);expect(response.headers.get('x-zod-environment')).toBe('staging');expect(response.headers.get('cache-control')).toBe('no-store');expect(await response.json()).toMatchObject({ok:true,environment:'staging',simulation:true,balance:{unit:'KAI_CARD_HOUR',precision:2,available:'100.00',reserved:'0.00',total:'100.00',version:1}});
    const mismatch=await fetch(`${base}/mobile/v1/staging/balance`,{headers:{'x-kai-e2e-session':env.STAGING_BUYER_TOKEN!}});expect(mismatch.status).toBe(409);expect(await mismatch.json()).toMatchObject({ok:false,environment:'staging',simulation:true,error:{code:'STAGING_ENVIRONMENT_MISMATCH'}});
    const conflict=await fetch(`${base}/mobile/v1/staging/balance`,{headers:{...headers(),authorization:'Bearer forbidden'}});expect(conflict.status).toBe(400);expect(await conflict.json()).toMatchObject({error:{code:'AUTH_SCHEME_CONFLICT'}});
  });

  it('keeps operator control behind both local role and independent control token',async()=>{const created=await fetch(`${base}/mobile/v1/staging/topups`,{method:'POST',headers:{...headers(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({amount:'100.00'})});const topup=(await created.json()).topup;
    const denied=await fetch(`${base}/staging/v1/operator/topups/${topup.id}/outcome`,{method:'POST',headers:{...headers(),'content-type':'application/json','idempotency-key':randomUUID(),'x-zod-staging-operator-token':env.STAGING_OPERATOR_CONTROL_TOKEN!},body:JSON.stringify({outcome:'succeeded',expectedVersion:1,reasonCode:'test'})});expect(denied.status).toBe(403);
    const allowed=await fetch(`${base}/staging/v1/operator/topups/${topup.id}/outcome`,{method:'POST',headers:{...headers(env.STAGING_OPERATOR_ACCESS_TOKEN!),'content-type':'application/json','idempotency-key':randomUUID(),'x-zod-staging-operator-token':env.STAGING_OPERATOR_CONTROL_TOKEN!},body:JSON.stringify({outcome:'succeeded',expectedVersion:1,reasonCode:'test'})});expect(allowed.status).toBe(200);expect(await allowed.json()).toMatchObject({topup:{status:'succeeded',allowedActions:['view_balance']},balance:{available:'199.80'}});
  });

  it('returns an inert access preview and permits only the buyer request-stop action',async()=>{const created=await fetch(`${base}/mobile/v1/staging/compute-orders`,{method:'POST',headers:{...headers(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({listingId:'71000000-0000-4000-8000-000000000001',quantity:'1.00'})});const order=(await created.json()).order;let version=order.version;
    for(const event of ['start_provisioning','mark_ready'] as const){const response=await fetch(`${base}/staging/v1/operator/compute-orders/${order.id}/fulfillment-transition`,{method:'POST',headers:{...operatorHeaders(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({event,expectedVersion:version})});expect(response.status).toBe(200);version=(await response.json()).order.version;}
    const preview=await fetch(`${base}/mobile/v1/staging/compute-orders/${order.id}/access-preview`,{headers:headers()});expect(preview.status).toBe(200);const body=await preview.json();expect(body.accessPreview).toMatchObject({mode:'demo_terminal',connectable:false,copyAllowed:false});expect(Object.keys(body.accessPreview)).not.toEqual(expect.arrayContaining(['host','ip','port','username','password','privateKey','token','ticket']));
    const running=await fetch(`${base}/staging/v1/operator/compute-orders/${order.id}/fulfillment-transition`,{method:'POST',headers:{...operatorHeaders(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({event:'start_running',expectedVersion:version})});version=(await running.json()).order.version;
    const stopped=await fetch(`${base}/mobile/v1/staging/compute-orders/${order.id}/request-stop`,{method:'POST',headers:{...headers(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({expectedVersion:version})});expect(stopped.status).toBe(200);expect(await stopped.json()).toMatchObject({order:{fulfillment:{status:'stopping'},allowedActions:[]}});
  });

  it('keeps CNY out of catalog/orders and isolates buyer resources by seeded principal',async()=>{const catalog=await fetch(`${base}/mobile/v1/staging/catalog`,{headers:headers()});const catalogBody=await catalog.json();expect(catalog.status).toBe(200);expect(JSON.stringify(catalogBody)).not.toMatch(/CNY|paymentAmount|currency/u);const orders=await fetch(`${base}/mobile/v1/staging/compute-orders`,{headers:headers()});const orderBody=await orders.json();expect(JSON.stringify(orderBody)).not.toMatch(/CNY|paymentAmount|currency/u);const foreign=await fetch(`${base}/mobile/v1/staging/compute-orders/${orderBody.items[0].id}`,{headers:headers(env.STAGING_CREATOR_TOKEN!)});expect(foreign.status).toBe(404);expect(await foreign.json()).toMatchObject({error:{code:'NOT_FOUND'}});});

  it('hides buyer order versions from other members and rejects non-buyers on every mobile order route',async()=>{const created=await fetch(`${base}/mobile/v1/staging/compute-orders`,{method:'POST',headers:{...headers(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({listingId:'71000000-0000-4000-8000-000000000001',quantity:'1.00'})}),order=(await created.json()).order;
    const foreignMutations=[
      {path:`${order.id}/cancel`,body:(version:number)=>({expectedVersion:version})},
      {path:`${order.id}/manual-delivery-requests`,body:(version:number)=>({expectedOrderVersion:version,sshPublicKeyId:randomUUID(),termsVersion:'staging-manual-delivery-v1'})},
      {path:`${order.id}/request-stop`,body:(version:number)=>({expectedVersion:version})},
      {path:`${order.id}/accept`,body:(version:number)=>({expectedVersion:version})},
      {path:`${order.id}/disputes`,body:(version:number)=>({expectedVersion:version,category:'other',description:'外部主体不得从版本差异推断任何订单信息。'})},
    ];
    for(const mutation of foreignMutations)for(const version of [order.version,order.version+99]){const response=await fetch(`${base}/mobile/v1/staging/compute-orders/${mutation.path}`,{method:'POST',headers:{...headers(env.STAGING_CREATOR_TOKEN!),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify(mutation.body(version))});expect(response.status).toBe(404);expect(await response.json()).toMatchObject({error:{code:'NOT_FOUND'}});}
    const nonBuyerRoutes=[
      {path:'',method:'POST',body:{listingId:'71000000-0000-4000-8000-000000000001',quantity:'1.00'}},
      {path:'',method:'GET'},
      {path:`/${order.id}`,method:'GET'},
      {path:`/${order.id}/cancel`,method:'POST',body:{expectedVersion:order.version}},
      {path:`/${order.id}/manual-delivery-requests`,method:'POST',body:{expectedOrderVersion:order.version,sshPublicKeyId:randomUUID(),termsVersion:'staging-manual-delivery-v1'}},
      {path:`/${order.id}/request-stop`,method:'POST',body:{expectedVersion:order.version}},
      {path:`/${order.id}/access-preview`,method:'GET'},
      {path:`/${order.id}/accept`,method:'POST',body:{expectedVersion:order.version}},
      {path:`/${order.id}/disputes`,method:'POST',body:{expectedVersion:order.version,category:'other',description:'非买方主体不能访问移动端订单路由。'}},
    ];
    for(const token of [env.STAGING_SUPPLIER_TOKEN!,env.STAGING_OPERATOR_ACCESS_TOKEN!])for(const route of nonBuyerRoutes){const response=await fetch(`${base}/mobile/v1/staging/compute-orders${route.path}`,{method:route.method,headers:{...headers(token),...(route.method==='POST'?{'content-type':'application/json','idempotency-key':randomUUID()}: {})},...(route.body?{body:JSON.stringify(route.body)}:{})});expect(response.status).toBe(403);expect(await response.json()).toMatchObject({error:{code:'FORBIDDEN'}});}
  });

  it('offers only supplier-private draft CRUD with strict validation and no publication action',async()=>{const body=supplierDraft(),requestKey=randomUUID(),supplierHeaders={...headers(env.STAGING_SUPPLIER_TOKEN!),'content-type':'application/json','idempotency-key':requestKey};
    const [created,replayed]=await Promise.all([fetch(`${base}/mobile/v1/staging/supplier/resource-drafts`,{method:'POST',headers:supplierHeaders,body:JSON.stringify(body)}),fetch(`${base}/mobile/v1/staging/supplier/resource-drafts`,{method:'POST',headers:supplierHeaders,body:JSON.stringify(body)})]);expect([created.status,replayed.status].sort()).toEqual([200,201]);const createdBody=await created.json(),replayedBody=await replayed.json();expect(createdBody.draft).toEqual(replayedBody.draft);expect(createdBody.draft).toMatchObject({status:'draft',visibility:'private',purchasable:false,version:1,completeness:{complete:true},allowedActions:['edit']});
    const id=createdBody.draft.id;const list=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts?limit=20`,{headers:headers(env.STAGING_SUPPLIER_TOKEN!)});expect(await list.json()).toMatchObject({items:[{id}],nextCursor:null});const detail=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts/${id}`,{headers:headers(env.STAGING_SUPPLIER_TOKEN!)});expect(await detail.json()).toMatchObject({draft:{id,version:1}});
    const updated=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts/${id}`,{method:'PATCH',headers:{...headers(env.STAGING_SUPPLIER_TOKEN!),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({expectedVersion:1,patch:{resource:{gpuCount:16},pricing:{amount:'12.00'}}})});expect(updated.status).toBe(200);expect(await updated.json()).toMatchObject({draft:{id,version:2,resource:{gpuCount:16},pricing:{amount:'12.00'},allowedActions:['edit']}});
    const stale=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts/${id}`,{method:'PATCH',headers:{...headers(env.STAGING_SUPPLIER_TOKEN!),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({expectedVersion:1,patch:{resource:{gpuCount:32}}})});expect(stale.status).toBe(409);expect(await stale.json()).toMatchObject({error:{code:'VERSION_CONFLICT',currentVersion:2}});
    for(const token of [env.STAGING_BUYER_TOKEN!,env.STAGING_OPERATOR_ACCESS_TOKEN!]){const denied=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts`,{headers:headers(token)});expect(denied.status).toBe(403);expect(await denied.json()).toMatchObject({error:{code:'FORBIDDEN'}});}
    const unknown=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts`,{method:'POST',headers:{...headers(env.STAGING_SUPPLIER_TOKEN!),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({...supplierDraft(),unexpected:'value'})});expect(unknown.status).toBe(422);expect(await unknown.json()).toMatchObject({error:{code:'VALIDATION_ERROR',details:{field:'unexpected',reason:'unknown_field'}}});
    const sensitive=supplierDraft();sensitive.resource.fulfillmentNotes='请使用 password=not-for-logs 连接';const rejected=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts`,{method:'POST',headers:{...headers(env.STAGING_SUPPLIER_TOKEN!),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify(sensitive)});expect(rejected.status).toBe(422);const rejectedText=await rejected.text();expect(rejectedText).toContain('sensitive_or_disallowed_content');expect(rejectedText).not.toContain('not-for-logs');
    const invalidPrice=supplierDraft();invalidPrice.pricing.amount='10.0';const priceRejected=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts`,{method:'POST',headers:{...headers(env.STAGING_SUPPLIER_TOKEN!),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify(invalidPrice)});expect(priceRejected.status).toBe(422);
    const invalidCapacity=supplierDraft();invalidCapacity.resource.capacityGpuHours='1.001';const capacityRejected=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts`,{method:'POST',headers:{...headers(env.STAGING_SUPPLIER_TOKEN!),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify(invalidCapacity)});expect(capacityRejected.status).toBe(422);
    const invalidWindow=supplierDraft();invalidWindow.deliveryPlan={...invalidWindow.deliveryPlan,startsAt:'2026-10-01T00:00:00.000Z',endsAt:'2026-09-01T00:00:00.000Z'};const windowRejected=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts`,{method:'POST',headers:{...headers(env.STAGING_SUPPLIER_TOKEN!),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify(invalidWindow)});expect(windowRejected.status).toBe(422);
    const catalog=await fetch(`${base}/mobile/v1/staging/catalog`,{headers:headers()});expect(JSON.stringify(await catalog.json())).not.toContain(id);const absent=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts/${id}/submit`,{method:'POST',headers:headers(env.STAGING_SUPPLIER_TOKEN!)});expect(absent.status).toBe(404);
  });

  it('collects only buyer-owned public keys and advances manual delivery behind operator dual control',async()=>{const publicKey=sshPublicKey(),createKeyHeaders={...headers(),'content-type':'application/json','idempotency-key':randomUUID()};const created=await fetch(`${base}/mobile/v1/staging/access/ssh-public-keys`,{method:'POST',headers:createKeyHeaders,body:JSON.stringify({clientKeyId:randomUUID(),label:'工作站公钥',publicKey,ownershipAttested:true})});expect(created.status).toBe(201);const createdText=await created.text();expect(createdText).not.toContain(publicKey.split(' ')[1]!);expect(createdText).not.toContain('discarded-comment');const ssh=(JSON.parse(createdText)).sshPublicKey;expect(ssh).toMatchObject({algorithm:'ssh-ed25519',status:'active',version:1,allowedActions:['rename','revoke']});
    for(const token of [env.STAGING_SUPPLIER_TOKEN!,env.STAGING_OPERATOR_ACCESS_TOKEN!]){const denied=await fetch(`${base}/mobile/v1/staging/access/ssh-public-keys`,{headers:headers(token)});expect(denied.status).toBe(403);}
    const foreign=await fetch(`${base}/mobile/v1/staging/access/ssh-public-keys/${ssh.id}`,{headers:headers(env.STAGING_CREATOR_TOKEN!)});expect(foreign.status).toBe(404);
    const unattested=await fetch(`${base}/mobile/v1/staging/access/ssh-public-keys`,{method:'POST',headers:{...headers(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({clientKeyId:randomUUID(),label:'未确认公钥',publicKey,ownershipAttested:false})});expect(unattested.status).toBe(422);expect(await unattested.json()).toMatchObject({error:{code:'OWNERSHIP_ATTESTATION_REQUIRED'}});
    const immutable=await fetch(`${base}/mobile/v1/staging/access/ssh-public-keys/${ssh.id}`,{method:'PATCH',headers:{...headers(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({expectedVersion:1,label:'新名称',publicKey})});expect(immutable.status).toBe(422);
    const privateMaterial='-----BEGIN OPENSSH PRIVATE KEY-----\nsecret-value\n-----END OPENSSH PRIVATE KEY-----';const privateRejected=await fetch(`${base}/mobile/v1/staging/access/ssh-public-keys`,{method:'POST',headers:{...headers(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({clientKeyId:randomUUID(),label:'禁止内容',publicKey:privateMaterial,ownershipAttested:true})});expect(privateRejected.status).toBe(422);const privateText=await privateRejected.text();expect(privateText).toContain('PRIVATE_KEY_FORBIDDEN');expect(privateText).not.toContain('secret-value');
    const orderResponse=await fetch(`${base}/mobile/v1/staging/compute-orders`,{method:'POST',headers:{...headers(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({listingId:'71000000-0000-4000-8000-000000000001',quantity:'1.00'})});const order=(await orderResponse.json()).order;expect(order.allowedActions).toEqual(['cancel','submit_manual_delivery']);const beforeBalance=await (await fetch(`${base}/mobile/v1/staging/balance`,{headers:headers()})).json();const beforeCatalog=await (await fetch(`${base}/mobile/v1/staging/catalog`,{headers:headers()})).json();
    const submitted=await fetch(`${base}/mobile/v1/staging/compute-orders/${order.id}/manual-delivery-requests`,{method:'POST',headers:{...headers(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({expectedOrderVersion:order.version,sshPublicKeyId:ssh.id,termsVersion:'staging-manual-delivery-v1'})});expect(submitted.status).toBe(201);const submittedBody=await submitted.json(),request=submittedBody.manualDeliveryRequest;expect(submittedBody.order).toMatchObject({version:2,fulfillment:{status:'queued'},allowedActions:['cancel'],manualDeliveryRequest:{status:'submitted'}});expect(JSON.stringify(submittedBody)).not.toMatch(/publicKey|normalizedPublicKey|host|port|password|privateKey|token|script/u);
    const revokeBlocked=await fetch(`${base}/mobile/v1/staging/access/ssh-public-keys/${ssh.id}/revoke`,{method:'POST',headers:{...headers(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({expectedVersion:1})});expect(revokeBlocked.status).toBe(409);expect(await revokeBlocked.json()).toMatchObject({error:{code:'SSH_KEY_IN_USE'}});
    const buyerOperatorDenied=await fetch(`${base}/staging/v1/operator/manual-delivery-requests/${request.id}`,{headers:{...headers(),'x-zod-staging-operator-token':env.STAGING_OPERATOR_CONTROL_TOKEN!}});expect(buyerOperatorDenied.status).toBe(403);const operatorDetail=await fetch(`${base}/staging/v1/operator/manual-delivery-requests/${request.id}`,{headers:operatorHeaders()});expect(operatorDetail.status).toBe(200);expect((await operatorDetail.json()).manualDeliveryRequest).toMatchObject({id:request.id,normalizedPublicKey:expect.stringMatching(/^ssh-ed25519 /u)});
    let expectedVersion=1;for(const event of ['verify_key','start_provisioning','mark_ready'] as const){const transition=await fetch(`${base}/staging/v1/operator/manual-delivery-requests/${request.id}/transition`,{method:'POST',headers:{...operatorHeaders(),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({event,expectedVersion,evidenceRef:`staging-manual:${randomUUID()}`})});expect(transition.status).toBe(200);const transitionBody=await transition.json();expectedVersion=transitionBody.manualDeliveryRequest.version;if(event==='mark_ready')expect(transitionBody).toMatchObject({manualDeliveryRequest:{status:'ready'},order:{fulfillment:{status:'ready'},allowedActions:['access_preview']}});}
    const afterBalance=await (await fetch(`${base}/mobile/v1/staging/balance`,{headers:headers()})).json();const afterCatalog=await (await fetch(`${base}/mobile/v1/staging/catalog`,{headers:headers()})).json();expect(afterBalance.balance).toEqual(beforeBalance.balance);expect(afterCatalog.items[0].capacityAvailable).toBe(beforeCatalog.items[0].capacityAvailable);
  });

  it('recovers the same private draft and version after a controlled service restart',async()=>{const body=supplierDraft(),created=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts`,{method:'POST',headers:{...headers(env.STAGING_SUPPLIER_TOKEN!),'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify(body)});expect(created.status).toBe(201);const before=(await created.json()).draft;await stopServer();await startServer();const recovered=await fetch(`${base}/mobile/v1/staging/supplier/resource-drafts/${before.id}`,{headers:headers(env.STAGING_SUPPLIER_TOKEN!)});expect(recovered.status).toBe(200);expect((await recovered.json()).draft).toEqual(before);});

  it('fails closed for non-staging production and for a production staging process without isolated persistence',()=>{const forbidden=spawnSync(process.execPath,['--import','tsx','staging-sandbox/server.ts'],{cwd:new URL('..',import.meta.url),env:{...env,NODE_ENV:'production',LOCAL_E2E:'true',ZOD_ENV:'production'},encoding:'utf8'});expect(forbidden.status).not.toBe(0);expect(`${forbidden.stdout}${forbidden.stderr}`).toContain('STAGING_SANDBOX_DISABLED');const memory=spawnSync(process.execPath,['--import','tsx','staging-sandbox/server.ts'],{cwd:new URL('..',import.meta.url),env:{...env,NODE_ENV:'production',LOCAL_E2E:'false',ZOD_ENV:'staging',STAGING_SANDBOX_ENABLED:'true',STAGING_DATABASE_PATH:'memory://'},encoding:'utf8'});expect(memory.status).not.toBe(0);expect(`${memory.stdout}${memory.stderr}`).toContain('STAGING_PERSISTENT_DATABASE_REQUIRED');});
});
