import { PGlite } from '@electric-sql/pglite';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { buildApp } from '../src/app.js';
import { loadConfig } from '../src/config.js';
import { SEEDED, StagingSandboxStore } from '../staging-sandbox/store.js';
import { parseOpenSshPublicKey } from '../staging-sandbox/ssh-public-key.js';

const tokens={buyer:'b'.repeat(48),creator:'c'.repeat(48),operator:'o'.repeat(48),supplier:'s'.repeat(48)};
const key=()=>crypto.randomUUID();
const sshString=(value:Buffer|string)=>{const bytes=Buffer.isBuffer(value)?value:Buffer.from(value);const length=Buffer.alloc(4);length.writeUInt32BE(bytes.length);return Buffer.concat([length,bytes]);};
const publicKey=(comment='ignored@example')=>{const blob=Buffer.concat([sshString('ssh-ed25519'),sshString(Buffer.alloc(32,7))]);return`ssh-ed25519 ${blob.toString('base64')} ${comment}`;};
const rsaKey=(bits:number)=>{const modulus=Buffer.alloc(Math.ceil(bits/8)+1,0xff);modulus[0]=0;const blob=Buffer.concat([sshString('ssh-rsa'),sshString(Buffer.from([1,0,1])),sshString(modulus)]);return`ssh-rsa ${blob.toString('base64')}`;};

async function fixture(){const db=new PGlite();const store=new StagingSandboxStore(db);await store.initialize(tokens);return{db,store};}
async function acceptOrder(store:StagingSandboxStore,id:string,subjectId:string,consumedQuantity:string){await store.transition(SEEDED.operator,id,{event:'start_provisioning',expectedVersion:1},key());await store.transition(SEEDED.operator,id,{event:'mark_ready',expectedVersion:2},key());await store.transition(SEEDED.operator,id,{event:'start_running',expectedVersion:3},key());await store.transition(SEEDED.operator,id,{event:'request_stop',expectedVersion:4},key());await store.transition(SEEDED.operator,id,{event:'mark_stopped',expectedVersion:5},key());await store.meter(SEEDED.operator,id,{consumedQuantity,expectedVersion:6,evidenceRef:`demo:${crypto.randomUUID()}`},key());return store.accept(subjectId,id,7,key());}

describe('isolated staging commerce sandbox',()=>{
  it('matches real ssh-keygen SHA256 fingerprints and accepts only canonical allowlisted public keys',()=>{const parsed=parseOpenSshPublicKey(publicKey());expect(parsed).toMatchObject({algorithm:'ssh-ed25519'});expect(parsed.fingerprint).toMatch(/^SHA256:[A-Za-z0-9+/]+$/u);expect(parsed.normalized).not.toContain('ignored@example');const directory=mkdtempSync(join(tmpdir(),'zod-ssh-fingerprint-')),filename=join(directory,'id.pub');try{writeFileSync(filename,`${publicKey()}\n`,{mode:0o600});const result=spawnSync('ssh-keygen',['-lf',filename,'-E','sha256'],{encoding:'utf8'});expect(result.status,result.stderr).toBe(0);expect(result.stdout).toContain(parsed.fingerprint);}finally{rmSync(directory,{recursive:true,force:true});}expect(()=>parseOpenSshPublicKey(rsaKey(2048))).toThrowError(expect.objectContaining({code:'INVALID_SSH_PUBLIC_KEY'}));expect(parseOpenSshPublicKey(rsaKey(3072)).algorithm).toBe('ssh-rsa');for(const invalid of ['-----BEGIN OPENSSH PRIVATE KEY-----\nsecret\n-----END OPENSSH PRIVATE KEY-----',`${publicKey()}\n${publicKey()}`,'command="id" '+publicKey(),publicKey('password=forbidden'),publicKey('script=forbidden'),publicKey().replace('ssh-ed25519','ssh-dss')])expect(()=>parseOpenSshPublicKey(invalid)).toThrow();});

  it('stores owner-scoped public-key metadata and drives manual delivery without moving credits or capacity',{timeout:30_000},async()=>{const{db,store}=await fixture();const clientKeyId=key(),idempotencyKey=key(),input={clientKeyId,label:'工作站公钥',publicKey:publicKey('discard-this-comment'),ownershipAttested:true as const};const [created,replay]=await Promise.all([store.createSshPublicKey(SEEDED.buyer,input,idempotencyKey),store.createSshPublicKey(SEEDED.buyer,input,idempotencyKey)]);expect([created.replayed,replay.replayed].sort()).toEqual([false,true]);expect(created.body).toEqual(replay.body);expect(JSON.stringify(created.body)).not.toMatch(/publicKey|discard-this-comment|AAAAC3/u);const ssh=created.body.sshPublicKey;expect(ssh).toMatchObject({clientKeyId,label:'工作站公钥',algorithm:'ssh-ed25519',status:'active',version:1,allowedActions:['rename','revoke'],lastUsedAt:null});await expect(store.sshPublicKey(SEEDED.creator,ssh.id)).rejects.toMatchObject({code:'NOT_FOUND'});const renamed=await store.renameSshPublicKey(SEEDED.buyer,ssh.id,1,'训练节点公钥',key());expect(renamed.body.sshPublicKey).toMatchObject({label:'训练节点公钥',version:2});
    const order=(await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key())).body.order,balanceBefore=await store.balance(SEEDED.buyer),capacityBefore=(await store.catalog(undefined,undefined,20))[0]!.capacityAvailable,submitKey=key();const [submitted,submitReplay]=await Promise.all([store.submitManualDelivery(SEEDED.buyer,order.id,{expectedOrderVersion:1,sshPublicKeyId:ssh.id,termsVersion:'staging-manual-delivery-v1'},submitKey),store.submitManualDelivery(SEEDED.buyer,order.id,{expectedOrderVersion:1,sshPublicKeyId:ssh.id,termsVersion:'staging-manual-delivery-v1'},submitKey)]);expect([submitted.replayed,submitReplay.replayed].sort()).toEqual([false,true]);expect(submitted.body).toEqual(submitReplay.body);const request=submitted.body.manualDeliveryRequest;expect(submitted.body.order).toMatchObject({version:2,fulfillment:{status:'queued'},allowedActions:['cancel'],manualDeliveryRequest:{id:request.id,status:'submitted',key:{id:ssh.id,label:'训练节点公钥',algorithm:'ssh-ed25519'},allowedActions:[]}});expect(JSON.stringify(submitted.body)).not.toMatch(/normalized|publicKey|discard-this-comment/u);expect(await store.balance(SEEDED.buyer)).toEqual(balanceBefore);expect((await store.catalog(undefined,undefined,20))[0]!.capacityAvailable).toBe(capacityBefore);await expect(store.revokeSshPublicKey(SEEDED.buyer,ssh.id,2,key())).rejects.toMatchObject({code:'SSH_KEY_IN_USE'});
    const operatorDetail=await store.operatorManualDelivery(request.id);expect(operatorDetail.normalizedPublicKey).toBe(parseOpenSshPublicKey(input.publicKey).normalized);expect(JSON.stringify(operatorDetail.safe)).not.toMatch(/normalized|publicKey|discard-this-comment/u);
    const verifyInput={event:'verify_key' as const,expectedVersion:1,evidenceRef:`staging-manual:${key()}`},verifyKey=key(),[advanced,transitionReplay]=await Promise.all([store.transitionManualDelivery(SEEDED.operator,request.id,verifyInput,verifyKey),store.transitionManualDelivery(SEEDED.operator,request.id,verifyInput,verifyKey)]);expect([advanced.replayed,transitionReplay.replayed].sort()).toEqual([false,true]);expect(advanced.body.manualDeliveryRequest).toMatchObject({status:'key_verified',version:2});let next=await store.transitionManualDelivery(SEEDED.operator,request.id,{event:'start_provisioning',expectedVersion:2,evidenceRef:`staging-manual:${key()}`},key());expect(next.body.order).toMatchObject({version:3,fulfillment:{status:'provisioning'}});next=await store.transitionManualDelivery(SEEDED.operator,request.id,{event:'mark_ready',expectedVersion:3,evidenceRef:`staging-manual:${key()}`},key());expect(next.body).toMatchObject({manualDeliveryRequest:{status:'ready',version:4},order:{version:4,fulfillment:{status:'ready'},allowedActions:['access_preview']}});expect(await store.balance(SEEDED.buyer)).toEqual(balanceBefore);expect((await store.catalog(undefined,undefined,20))[0]!.capacityAvailable).toBe(capacityBefore);expect((await store.sshPublicKey(SEEDED.buyer,ssh.id)).lastUsedAt).not.toBeNull();await expect(store.revokeSshPublicKey(SEEDED.buyer,ssh.id,2,key())).rejects.toMatchObject({code:'SSH_KEY_IN_USE'});await store.transition(SEEDED.operator,order.id,{event:'start_running',expectedVersion:4},key());await store.transition(SEEDED.operator,order.id,{event:'request_stop',expectedVersion:5},key());await store.transition(SEEDED.operator,order.id,{event:'mark_stopped',expectedVersion:6},key());await store.meter(SEEDED.operator,order.id,{consumedQuantity:'0.00',expectedVersion:7,evidenceRef:`demo:${key()}`},key());await store.accept(SEEDED.buyer,order.id,8,key());expect((await store.revokeSshPublicKey(SEEDED.buyer,ssh.id,2,key())).body.sshPublicKey.status).toBe('revoked');
    const eventPayloads=(await db.query<{payload:unknown}>('SELECT payload FROM sandbox_outbox WHERE entity_id=$1 OR entity_id=$2',[ssh.id,request.id])).rows;expect(JSON.stringify(eventPayloads)).not.toMatch(/discard-this-comment|AAAAC3|normalized_public_key/u);expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('rejects failed provisioning safely and permits a new request or key revocation',{timeout:30_000},async()=>{const{db,store}=await fixture();const first=(await store.createSshPublicKey(SEEDED.buyer,{clientKeyId:key(),label:'第一把公钥',publicKey:publicKey('first'),ownershipAttested:true},key())).body.sshPublicKey;const order=(await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key())).body.order,balanceBefore=await store.balance(SEEDED.buyer),capacityBefore=(await store.catalog(undefined,undefined,20))[0]!.capacityAvailable;const submitted=(await store.submitManualDelivery(SEEDED.buyer,order.id,{expectedOrderVersion:1,sshPublicKeyId:first.id,termsVersion:'staging-manual-delivery-v1'},key())).body.manualDeliveryRequest;await store.transitionManualDelivery(SEEDED.operator,submitted.id,{event:'verify_key',expectedVersion:1,evidenceRef:`staging-manual:${key()}`},key());await store.transitionManualDelivery(SEEDED.operator,submitted.id,{event:'start_provisioning',expectedVersion:2,evidenceRef:`staging-manual:${key()}`},key());const rejected=await store.transitionManualDelivery(SEEDED.operator,submitted.id,{event:'reject',expectedVersion:3,evidenceRef:`staging-manual:${key()}`,reasonCode:'capacity_unavailable'},key());expect(rejected.body).toMatchObject({manualDeliveryRequest:{status:'rejected',version:4},order:{version:4,fulfillment:{status:'queued'},allowedActions:['cancel','submit_manual_delivery']}});expect(await store.balance(SEEDED.buyer)).toEqual(balanceBefore);expect((await store.catalog(undefined,undefined,20))[0]!.capacityAvailable).toBe(capacityBefore);expect((await store.revokeSshPublicKey(SEEDED.buyer,first.id,1,key())).body.sshPublicKey.status).toBe('revoked');const replacementBlob=Buffer.concat([sshString('ssh-ed25519'),sshString(Buffer.alloc(32,8))]);const replacement=(await store.createSshPublicKey(SEEDED.buyer,{clientKeyId:key(),label:'第二把公钥',publicKey:`ssh-ed25519 ${replacementBlob.toString('base64')}`,ownershipAttested:true},key())).body.sshPublicKey;const resubmitted=await store.submitManualDelivery(SEEDED.buyer,order.id,{expectedOrderVersion:4,sshPublicKeyId:replacement.id,termsVersion:'staging-manual-delivery-v1'},key());const canceled=await store.cancelOrder(SEEDED.buyer,order.id,5,key());expect(canceled.body.order).toMatchObject({status:'canceled',manualDeliveryRequest:{id:resubmitted.body.manualDeliveryRequest.id,status:'canceled'}});expect((await store.revokeSshPublicKey(SEEDED.buyer,replacement.id,1,key())).body.sshPublicKey).toMatchObject({status:'revoked',version:2,allowedActions:[]});expect(await store.ledgerConservation()).toBe(0n);await db.close();});
  const draftInput=(clientDraftId=key())=>({
    clientDraftId,
    resource:{name:'H100 算力资源',gpuModel:'H100',gpuCardType:'SXM' as const,gpuCount:8,gpuMemoryGb:80,
      regionCode:'CN-SH' as const,city:'上海',machineType:'bare_metal' as const,cpuModel:'Xeon Platinum',cpuCores:96,
      memoryGb:2048,storageGb:7000,networkMbps:10000,operatingSystem:'ubuntu_22_04' as const,
      capacityGpuHours:'1000.00',fulfillmentNotes:'按约定的可用时间段准备资源。'},
    deliveryPlan:{mode:'scheduled_window' as const,startsAt:'2026-09-01T00:00:00.000Z',endsAt:'2026-10-01T00:00:00.000Z',timezone:'Asia/Shanghai',leadTimeHours:null},
    pricing:{unit:'KAI_CARD_HOUR_PER_GPU_HOUR' as const,amount:'10.00'},
    acknowledgements:{ownershipConfirmed:true,remoteAccessSafetyAcknowledged:true},
  });

  it('persists private supplier drafts with atomic idempotency, versions, audit and outbox',{timeout:30_000},async()=>{const{db,store}=await fixture();
    const input=draftInput(),requestKey=key();const [first,replay]=await Promise.all([
      store.createSupplierResourceDraft(SEEDED.supplier,input,requestKey),store.createSupplierResourceDraft(SEEDED.supplier,input,requestKey),
    ]);expect([first.replayed,replay.replayed].sort()).toEqual([false,true]);expect(first.body).toEqual(replay.body);expect(first.body.draft).toMatchObject({status:'draft',version:1,visibility:'private',purchasable:false,completeness:{complete:true,missingFields:[]},allowedActions:['edit'],simulation:true});
    await expect(store.createSupplierResourceDraft(SEEDED.supplier,{...input,pricing:{...input.pricing,amount:'11.00'}},requestKey)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});
    const sameClient=await store.createSupplierResourceDraft(SEEDED.supplier,input,key());expect(sameClient.status).toBe(200);expect(sameClient.body.draft.id).toBe(first.body.draft.id);
    const concurrentClient=draftInput(),[clientOne,clientTwo]=await Promise.all([
      store.createSupplierResourceDraft(SEEDED.supplier,concurrentClient,key()),store.createSupplierResourceDraft(SEEDED.supplier,concurrentClient,key()),
    ]);expect(clientOne.body.draft.id).toBe(clientTwo.body.draft.id);
    const updateKey=key(),[updated,replayedUpdate]=await Promise.all([
      store.updateSupplierResourceDraft(SEEDED.supplier,first.body.draft.id,1,{resource:{gpuCount:16},pricing:{amount:'12.00'}},updateKey),
      store.updateSupplierResourceDraft(SEEDED.supplier,first.body.draft.id,1,{resource:{gpuCount:16},pricing:{amount:'12.00'}},updateKey),
    ]);expect([updated.replayed,replayedUpdate.replayed].sort()).toEqual([false,true]);expect(updated.body).toEqual(replayedUpdate.body);expect(updated.body.draft).toMatchObject({version:2,resource:{gpuCount:16},pricing:{amount:'12.00'},visibility:'private',purchasable:false});
    await expect(store.updateSupplierResourceDraft(SEEDED.supplier,first.body.draft.id,1,{resource:{gpuCount:17}},updateKey)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});
    await expect(store.updateSupplierResourceDraft(SEEDED.supplier,first.body.draft.id,1,{resource:{gpuCount:32}},key())).rejects.toMatchObject({code:'VERSION_CONFLICT',currentVersion:2});
    expect(await store.supplierResourceDraft(SEEDED.supplier,first.body.draft.id)).toEqual(updated.body.draft);expect(await store.supplierResourceDrafts(SEEDED.supplier,10,0)).toHaveLength(2);
    expect((await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_supplier_resource_drafts')).rows[0]!.count).toBe('2');
    expect((await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_audit WHERE entity_type=\'supplier_resource_draft\' AND entity_id=$1',[first.body.draft.id])).rows[0]!.count).toBe('2');
    expect((await db.query<{topic:string;payload:unknown}>('SELECT topic,payload FROM sandbox_outbox WHERE entity_id=$1 ORDER BY created_at',[first.body.draft.id])).rows).toEqual([
      {topic:'staging.supplier_resource_draft.created',payload:{changedFields:['resource','deliveryPlan','pricing','acknowledgements'],version:1,requestId:'internal-test'}},
      {topic:'staging.supplier_resource_draft.updated',payload:{changedFields:['pricing','resource'],version:2,requestId:'internal-test'}},
    ]);await db.close();});

  it('keeps drafts owner-scoped and leaves catalog, orders and ledgers unchanged',{timeout:30_000},async()=>{const{db,store}=await fixture();const otherId=key();await db.query(`INSERT INTO sandbox_subjects(id,handle,role,token_hash,version,simulation,environment) VALUES($1,'supplier-two','supplier',$2,1,true,'staging')`,[otherId,'f'.repeat(64)]);const before={catalog:(await store.catalog(undefined,undefined,20)).length,orders:(await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_orders')).rows[0]!.count,ledger:(await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_ledger_entries')).rows[0]!.count};const created=await store.createSupplierResourceDraft(SEEDED.supplier,draftInput(),key());await expect(store.supplierResourceDraft(otherId,created.body.draft.id)).rejects.toMatchObject({code:'NOT_FOUND'});await expect(store.updateSupplierResourceDraft(otherId,created.body.draft.id,1,{resource:{gpuCount:2}},key())).rejects.toMatchObject({code:'NOT_FOUND'});expect(await store.supplierResourceDrafts(otherId,10,0)).toEqual([]);expect((await store.catalog(undefined,undefined,20)).length).toBe(before.catalog);expect((await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_orders')).rows[0]!.count).toBe(before.orders);expect((await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_ledger_entries')).rows[0]!.count).toBe(before.ledger);await db.close();});

  it('reports the locked completeness field set without implying publication',{timeout:30_000},async()=>{const{db,store}=await fixture();const base=draftInput(),created=await store.createSupplierResourceDraft(SEEDED.supplier,{...base,resource:{...base.resource,name:null,gpuModel:null,gpuCardType:null,gpuCount:null,gpuMemoryGb:null,regionCode:null,networkMbps:null,capacityGpuHours:null},deliveryPlan:null,pricing:{...base.pricing,amount:null},acknowledgements:{ownershipConfirmed:false,remoteAccessSafetyAcknowledged:false}},key());expect(created.body.draft).toMatchObject({status:'draft',visibility:'private',purchasable:false,completeness:{complete:false,missingFields:['resource.name','resource.gpuModel','resource.gpuCardType','resource.gpuCount','resource.gpuMemoryGb','resource.regionCode','resource.networkMbps','resource.capacityGpuHours','pricing.amount','deliveryPlan','acknowledgements.ownershipConfirmed','acknowledgements.remoteAccessSafetyAcknowledged']},allowedActions:['edit']});await db.close();});

  it('converts demo CNY deterministically, credits once, and preserves idempotency',{timeout:30_000},async()=>{const{db,store}=await fixture();
    for(const [amount,credit] of [['1.00','0.99'],['1.01','1.00'],['100.00','99.80'],['1000.00','998.00']] as const){const created=await store.createTopup(SEEDED.buyer,amount,key());expect(created.body.topup).toMatchObject({paymentAmount:amount,creditAmount:credit,status:'processing',channel:'demo',version:1});}
    const requestKey=key(),[created,replay]=await Promise.all([store.createTopup(SEEDED.buyer,'100.00',requestKey),store.createTopup(SEEDED.buyer,'100.00',requestKey)]);expect([created.replayed,replay.replayed].sort()).toEqual([false,true]);expect(replay.body).toEqual(created.body);await expect(store.createTopup(SEEDED.buyer,'101.00',requestKey)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});
    const outcomeKey=key(),succeeded=await store.topupOutcome(SEEDED.operator,created.body.topup.id,{outcome:'succeeded',expectedVersion:1,reasonCode:'demo_success'},outcomeKey);expect(succeeded.body).toMatchObject({topup:{status:'succeeded',creditAmount:'99.80'},balance:{available:'199.80',reserved:'0.00'}});expect((await store.topupOutcome(SEEDED.operator,created.body.topup.id,{outcome:'succeeded',expectedVersion:1,reasonCode:'demo_success'},outcomeKey)).replayed).toBe(true);await expect(store.topupOutcome(SEEDED.operator,created.body.topup.id,{outcome:'failed',expectedVersion:2,reasonCode:'changed'},key())).rejects.toMatchObject({code:'TOPUP_ALREADY_FINAL'});expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('reserves demo credits and capacity, drives the exact action matrix, meters and accepts',{timeout:30_000},async()=>{const{db,store}=await fixture();const created=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key());expect(created.body).toMatchObject({order:{status:'reserved',version:1,totalCredits:'10.00',reservedCredits:'10.00',fulfillment:{status:'queued'},allowedActions:['cancel','submit_manual_delivery']},balance:{available:'90.00',reserved:'10.00'}});const id=created.body.order.id;
    let order=(await store.transition(SEEDED.operator,id,{event:'start_provisioning',expectedVersion:1},key())).body.order;expect(order).toMatchObject({fulfillment:{status:'provisioning'},allowedActions:[]});order=(await store.transition(SEEDED.operator,id,{event:'mark_ready',expectedVersion:2},key())).body.order;expect(order.allowedActions).toEqual(['access_preview']);order=(await store.transition(SEEDED.operator,id,{event:'start_running',expectedVersion:3},key())).body.order;expect(order.allowedActions).toEqual(['access_preview','request_stop','open_dispute']);order=(await store.connection(SEEDED.operator,id,{event:'lost',expectedVersion:4,reasonCode:'demo_disconnect'},key())).body.order;expect(order).toMatchObject({fulfillment:{status:'disconnected'},allowedActions:['request_stop','open_dispute']});order=(await store.connection(SEEDED.operator,id,{event:'restored',expectedVersion:5,reasonCode:'demo_restore'},key())).body.order;expect(order.allowedActions).toEqual(['access_preview','request_stop','open_dispute']);order=(await store.transition(SEEDED.operator,id,{event:'request_stop',expectedVersion:6},key())).body.order;expect(order.allowedActions).toEqual([]);order=(await store.transition(SEEDED.operator,id,{event:'mark_stopped',expectedVersion:7},key())).body.order;expect(order.allowedActions).toEqual([]);order=(await store.meter(SEEDED.operator,id,{consumedQuantity:'0.60',expectedVersion:8,evidenceRef:`demo:${crypto.randomUUID()}`},key())).body.order;expect(order).toMatchObject({status:'acceptance_pending',allowedActions:['accept','open_dispute'],metering:{reservedCredits:'10.00',consumedCredits:'6.00',refundableCredits:'4.00'}});const accepted=await store.accept(SEEDED.buyer,id,9,key());expect(accepted.body).toMatchObject({order:{status:'accepted',allowedActions:[]},balance:{available:'94.00',reserved:'0.00'}});expect((await store.catalog(undefined,undefined,20))[0]).toMatchObject({capacityAvailable:'199.40'});expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('owner-scopes every buyer order mutation before version checks and leaves no rejected writes',{timeout:30_000},async()=>{const{db,store}=await fixture();const order=(await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key())).body.order,sshPublicKeyId=key();
    const snapshot=async()=>({
      order:(await db.query<Record<string,unknown>>(`SELECT status,fulfillment_status,connection_status,version,updated_at::text AS updated_at FROM sandbox_orders WHERE id=$1`,[order.id])).rows[0],
      ledger:(await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_ledger_entries')).rows[0]!.count,
      audit:(await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_audit')).rows[0]!.count,
      outbox:(await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_outbox')).rows[0]!.count,
      idempotency:(await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_idempotency')).rows[0]!.count,
      disputes:(await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_disputes')).rows[0]!.count,
      manualDelivery:(await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_manual_delivery_requests')).rows[0]!.count,
    }),before=await snapshot();
    const mutations=[
      (expectedVersion:number)=>store.cancelOrder(SEEDED.creator,order.id,expectedVersion,key()),
      (expectedVersion:number)=>store.submitManualDelivery(SEEDED.creator,order.id,{expectedOrderVersion:expectedVersion,sshPublicKeyId,termsVersion:'staging-manual-delivery-v1'},key()),
      (expectedVersion:number)=>store.requestStop(SEEDED.creator,order.id,expectedVersion,key()),
      (expectedVersion:number)=>store.accept(SEEDED.creator,order.id,expectedVersion,key()),
      (expectedVersion:number)=>store.openDispute(SEEDED.creator,order.id,{expectedVersion,category:'other',description:'外部主体不得从版本差异推断任何订单信息。'},key()),
    ];
    for(const mutate of mutations)for(const expectedVersion of [order.version,order.version+99])await expect(mutate(expectedVersion)).rejects.toMatchObject({code:'NOT_FOUND',statusCode:404});
    expect(await snapshot()).toEqual(before);expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('prevents overselling and pays commission only from final captured card-hours',{timeout:30_000},async()=>{const{db,store}=await fixture();const link=(await store.referralLink(SEEDED.creator,key())).body.referralLink;await store.attribute(SEEDED.buyer,link.token,key());const topup=await store.createTopup(SEEDED.buyer,'100000.00',key());await store.topupOutcome(SEEDED.operator,topup.body.topup.id,{outcome:'succeeded',expectedVersion:1,reasonCode:'fund_capacity_test'},key());const full=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'200.00'},key());await expect(store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'0.01'},key())).rejects.toMatchObject({code:'DEMO_CAPACITY_UNAVAILABLE'});await expect(store.reconcile(SEEDED.operator,full.body.order.id,{event:'source_completed',expectedVersion:1},key())).rejects.toMatchObject({code:'INVALID_STATE'});await expect(store.reconcile(SEEDED.operator,full.body.order.id,{event:'mature_observation',expectedVersion:1},key())).rejects.toMatchObject({code:'INVALID_STATE'});await expect(store.transfer(SEEDED.creator,key())).rejects.toMatchObject({code:'INVALID_STATE'});await acceptOrder(store,full.body.order.id,SEEDED.buyer,'0.60');const completed=await store.reconcile(SEEDED.operator,full.body.order.id,{event:'source_completed',expectedVersion:1},key());expect(completed.body.commission.commissionCardHours).toBe('0.06');await store.reconcile(SEEDED.operator,full.body.order.id,{event:'mature_observation',expectedVersion:2},key());const fundingBeforeTransfer=(await db.query<{balance:string}>(`SELECT balance_micros::text AS balance FROM sandbox_accounts WHERE subject_id IS NULL AND kind='demo_funding'`)).rows[0]!.balance;const transfer=await store.transfer(SEEDED.creator,key());expect(transfer.body.transfer).toMatchObject({cardHours:'0.06',rewardEvent:{status:'pending',allowedActions:['consume'],simulation:true}});expect((await db.query<{balance:string}>(`SELECT balance_micros::text AS balance FROM sandbox_accounts WHERE subject_id IS NULL AND kind='demo_funding'`)).rows[0]!.balance).toBe(fundingBeforeTransfer);expect((await store.rewards(SEEDED.creator,20))).toHaveLength(1);await expect(store.transfer(SEEDED.creator,key())).rejects.toMatchObject({code:'INVALID_STATE'});expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('serializes concurrent capacity reservations and isolates failed/canceled topups from the ledger',{timeout:30_000},async()=>{const{db,store}=await fixture();for(const outcome of ['failed','canceled'] as const){const topup=await store.createTopup(SEEDED.buyer,'100.00',key());await store.topupOutcome(SEEDED.operator,topup.body.topup.id,{outcome,expectedVersion:1,reasonCode:`demo_${outcome}`},key());}expect(await store.balance(SEEDED.buyer)).toMatchObject({available:'100.00',reserved:'0.00'});
    const funded=await store.createTopup(SEEDED.buyer,'100000.00',key());await store.topupOutcome(SEEDED.operator,funded.body.topup.id,{outcome:'succeeded',expectedVersion:1,reasonCode:'fund_concurrency'},key());const results=await Promise.allSettled([store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'150.00'},key()),store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'150.00'},key())]);expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);expect(results.filter(result=>result.status==='rejected')).toHaveLength(1);expect((results.find(result=>result.status==='rejected') as PromiseRejectedResult).reason).toMatchObject({code:'DEMO_CAPACITY_UNAVAILABLE'});expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('resolves running/disconnected disputes without contradictory capacity or ledger states',{timeout:30_000},async()=>{const{db,store}=await fixture();
    const running=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key());await store.transition(SEEDED.operator,running.body.order.id,{event:'start_provisioning',expectedVersion:1},key());await store.transition(SEEDED.operator,running.body.order.id,{event:'mark_ready',expectedVersion:2},key());await store.transition(SEEDED.operator,running.body.order.id,{event:'start_running',expectedVersion:3},key());const fullDispute=await store.openDispute(SEEDED.buyer,running.body.order.id,{expectedVersion:4,category:'access',description:'演示连接无法使用，需要核对并全额退款。'},key());const full=await store.resolveDispute(SEEDED.operator,fullDispute.body.dispute.id,{outcome:'full_refund',expectedVersion:1,reasonCode:'demo_full_refund'},key());expect(full.body).toMatchObject({order:{status:'refunded',fulfillment:{status:'failed',connectionStatus:'stopped'}},balance:{available:'100.00',reserved:'0.00'}});expect((await store.catalog(undefined,undefined,20))[0]?.capacityAvailable).toBe('200.00');
    const partialOrder=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key());await store.transition(SEEDED.operator,partialOrder.body.order.id,{event:'start_provisioning',expectedVersion:1},key());await store.transition(SEEDED.operator,partialOrder.body.order.id,{event:'mark_ready',expectedVersion:2},key());await store.transition(SEEDED.operator,partialOrder.body.order.id,{event:'start_running',expectedVersion:3},key());const partialDispute=await store.openDispute(SEEDED.buyer,partialOrder.body.order.id,{expectedVersion:4,category:'metering',description:'演示计量需要人工核对后再决定部分退款。'},key());await expect(store.resolveDispute(SEEDED.operator,partialDispute.body.dispute.id,{outcome:'partial_refund',refundCredits:'5.00',expectedVersion:1,reasonCode:'too_early'},key())).rejects.toMatchObject({code:'INVALID_STATE'});await store.transition(SEEDED.operator,partialOrder.body.order.id,{event:'request_stop',expectedVersion:5},key());await store.transition(SEEDED.operator,partialOrder.body.order.id,{event:'mark_stopped',expectedVersion:6},key());await store.meter(SEEDED.operator,partialOrder.body.order.id,{consumedQuantity:'0.60',expectedVersion:7,evidenceRef:`demo:${crypto.randomUUID()}`},key());const partial=await store.resolveDispute(SEEDED.operator,partialDispute.body.dispute.id,{outcome:'partial_refund',refundCredits:'5.00',expectedVersion:1,reasonCode:'metered_partial'},key());expect(partial.body).toMatchObject({order:{status:'accepted',fulfillment:{status:'stopped',connectionStatus:'stopped'}},balance:{available:'95.00',reserved:'0.00'}});
    const disconnected=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key());await store.transition(SEEDED.operator,disconnected.body.order.id,{event:'start_provisioning',expectedVersion:1},key());await store.transition(SEEDED.operator,disconnected.body.order.id,{event:'mark_ready',expectedVersion:2},key());await store.transition(SEEDED.operator,disconnected.body.order.id,{event:'start_running',expectedVersion:3},key());await store.connection(SEEDED.operator,disconnected.body.order.id,{event:'lost',expectedVersion:4,reasonCode:'demo_lost'},key());const rejectedDispute=await store.openDispute(SEEDED.buyer,disconnected.body.order.id,{expectedVersion:5,category:'disconnect',description:'演示连接中断，需要停止计量后再裁决。'},key());await expect(store.resolveDispute(SEEDED.operator,rejectedDispute.body.dispute.id,{outcome:'reject_refund',expectedVersion:1,reasonCode:'too_early'},key())).rejects.toMatchObject({code:'INVALID_STATE'});await store.transition(SEEDED.operator,disconnected.body.order.id,{event:'request_stop',expectedVersion:6},key());await store.transition(SEEDED.operator,disconnected.body.order.id,{event:'mark_stopped',expectedVersion:7},key());await store.meter(SEEDED.operator,disconnected.body.order.id,{consumedQuantity:'0.50',expectedVersion:8,evidenceRef:`demo:${crypto.randomUUID()}`},key());const rejected=await store.resolveDispute(SEEDED.operator,rejectedDispute.body.dispute.id,{outcome:'reject_refund',expectedVersion:1,reasonCode:'metered_reject'},key());expect(rejected.body).toMatchObject({dispute:{refundCredits:'5.00'},order:{status:'accepted',fulfillment:{status:'stopped'}},balance:{available:'90.00',reserved:'0.00'}});expect((await store.catalog(undefined,undefined,20))[0]?.capacityAvailable).toBe('198.90');expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('reverses canceled, failed, refunded and observed commissions from authoritative order facts',{timeout:30_000},async()=>{const{db,store}=await fixture();const link=(await store.referralLink(SEEDED.creator,key())).body.referralLink;await store.attribute(SEEDED.buyer,link.token,key());
    const canceled=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key());await store.cancelOrder(SEEDED.buyer,canceled.body.order.id,1,key());await expect(store.transition(SEEDED.operator,canceled.body.order.id,{event:'start_provisioning',expectedVersion:2},key())).rejects.toMatchObject({code:'INVALID_STATE'});expect((await store.reconcile(SEEDED.operator,canceled.body.order.id,{event:'source_refunded',expectedVersion:1},key())).body.commission).toMatchObject({status:'reversed',commissionCardHours:'0.00'});
    const failed=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key());await store.transition(SEEDED.operator,failed.body.order.id,{event:'start_provisioning',expectedVersion:1},key());await store.transition(SEEDED.operator,failed.body.order.id,{event:'fail_provisioning',expectedVersion:2,reasonCode:'demo_failed'},key());expect((await store.reconcile(SEEDED.operator,failed.body.order.id,{event:'source_refunded',expectedVersion:1},key())).body.commission.status).toBe('reversed');
    const refunded=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key());await store.transition(SEEDED.operator,refunded.body.order.id,{event:'start_provisioning',expectedVersion:1},key());await store.transition(SEEDED.operator,refunded.body.order.id,{event:'mark_ready',expectedVersion:2},key());await store.transition(SEEDED.operator,refunded.body.order.id,{event:'start_running',expectedVersion:3},key());const refundDispute=await store.openDispute(SEEDED.buyer,refunded.body.order.id,{expectedVersion:4,category:'access',description:'演示运行资源需要全额退款并结束履约。'},key());await store.resolveDispute(SEEDED.operator,refundDispute.body.dispute.id,{outcome:'full_refund',expectedVersion:1,reasonCode:'terminal_refund'},key());expect((await store.reconcile(SEEDED.operator,refunded.body.order.id,{event:'source_refunded',expectedVersion:1},key())).body.commission).toMatchObject({status:'reversed',commissionCardHours:'0.00'});
    const observed=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key());await acceptOrder(store,observed.body.order.id,SEEDED.buyer,'0.60');await store.reconcile(SEEDED.operator,observed.body.order.id,{event:'source_completed',expectedVersion:1},key());await store.reconcile(SEEDED.operator,observed.body.order.id,{event:'mature_observation',expectedVersion:2},key());const reversed=await store.reconcile(SEEDED.operator,observed.body.order.id,{event:'source_refunded',expectedVersion:3},key());expect(reversed.body.commission).toMatchObject({status:'reversed',commissionCardHours:'0.06'});expect(await store.order(observed.body.order.id,SEEDED.buyer)).toMatchObject({status:'refunded'});expect(await store.balance(SEEDED.buyer)).toMatchObject({available:'100.00',reserved:'0.00'});expect((await store.catalog(undefined,undefined,20))[0]?.capacityAvailable).toBe('200.00');expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('resets only the selected simulation subject while preserving append-only audit and replay',{timeout:30_000},async()=>{const{db,store}=await fixture();const topup=await store.createTopup(SEEDED.buyer,'100.00',key());await store.topupOutcome(SEEDED.operator,topup.body.topup.id,{outcome:'succeeded',expectedVersion:1,reasonCode:'before_reset'},key());await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key());const before=(await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_audit')).rows[0]!.count,resetKey=key();const reset=await store.reset(SEEDED.operator,SEEDED.buyer,{confirmation:'RESET STAGING SUBJECT',expectedVersion:1},resetKey);expect(reset.body.newBalance).toMatchObject({available:'100.00',reserved:'0.00',total:'100.00'});const replay=await store.reset(SEEDED.operator,SEEDED.buyer,{confirmation:'RESET STAGING SUBJECT',expectedVersion:1},resetKey);expect(replay.replayed).toBe(true);expect(replay.body).toEqual(reset.body);expect(await store.orders(SEEDED.buyer,undefined,20)).toEqual([]);expect(await store.topups(SEEDED.buyer,20)).toEqual([]);expect(Number((await db.query<{count:string}>('SELECT count(*)::text AS count FROM sandbox_audit')).rows[0]!.count)).toBeGreaterThan(Number(before));expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('preserves another subject consumed capacity when resetting canceled target orders',{timeout:30_000},async()=>{const{db,store}=await fixture();const creatorFunds=await store.createTopup(SEEDED.creator,'100.00',key());await store.topupOutcome(SEEDED.operator,creatorFunds.body.topup.id,{outcome:'succeeded',expectedVersion:1,reasonCode:'second_buyer_seed'},key());const foreign=await store.createOrder(SEEDED.creator,{listingId:SEEDED.listing,quantity:'1.00'},key());await acceptOrder(store,foreign.body.order.id,SEEDED.creator,'1.00');const target=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'5.00'},key());await store.cancelOrder(SEEDED.buyer,target.body.order.id,1,key());expect((await store.catalog(undefined,undefined,20))[0]?.capacityAvailable).toBe('199.00');await store.reset(SEEDED.operator,SEEDED.buyer,{confirmation:'RESET STAGING SUBJECT',expectedVersion:1},key());expect((await store.catalog(undefined,undefined,20))[0]?.capacityAvailable).toBe('199.00');expect(await store.order(foreign.body.order.id,SEEDED.creator)).toMatchObject({status:'accepted',quantity:'1.00'});expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('rolls back only the target accepted inventory and supplier settlement during reset',{timeout:30_000},async()=>{const{db,store}=await fixture();const target=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key());await acceptOrder(store,target.body.order.id,SEEDED.buyer,'0.60');expect((await store.catalog(undefined,undefined,20))[0]?.capacityAvailable).toBe('199.40');expect((await db.query<{balance:string}>(`SELECT balance_micros::text AS balance FROM sandbox_accounts WHERE subject_id=$1 AND kind='supplier_earned'`,[SEEDED.supplier])).rows[0]?.balance).toBe('6000000');await store.reset(SEEDED.operator,SEEDED.buyer,{confirmation:'RESET STAGING SUBJECT',expectedVersion:1},key());expect((await store.catalog(undefined,undefined,20))[0]?.capacityAvailable).toBe('200.00');expect((await db.query<{balance:string}>(`SELECT balance_micros::text AS balance FROM sandbox_accounts WHERE subject_id=$1 AND kind='supplier_earned'`,[SEEDED.supplier])).rows[0]?.balance).toBe('0');expect(await store.balance(SEEDED.buyer)).toMatchObject({available:'100.00',reserved:'0.00'});expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('refuses buyer reset when its orders carry another creator commission',{timeout:30_000},async()=>{const{db,store}=await fixture();const link=(await store.referralLink(SEEDED.creator,key())).body.referralLink;await store.attribute(SEEDED.buyer,link.token,key());const order=await store.createOrder(SEEDED.buyer,{listingId:SEEDED.listing,quantity:'1.00'},key());await expect(store.reset(SEEDED.operator,SEEDED.buyer,{confirmation:'RESET STAGING SUBJECT',expectedVersion:1},key())).rejects.toMatchObject({code:'INVALID_STATE'});expect(await store.order(order.body.order.id,SEEDED.buyer)).toMatchObject({status:'reserved'});expect((await store.commissions(SEEDED.creator)).commissions).toHaveLength(1);expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('refuses cross-subject reset effects and does not invent a creator seed balance',{timeout:30_000},async()=>{const{db,store}=await fixture();const link=(await store.referralLink(SEEDED.creator,key())).body.referralLink;await store.attribute(SEEDED.buyer,link.token,key());await expect(store.reset(SEEDED.operator,SEEDED.creator,{confirmation:'RESET STAGING SUBJECT',expectedVersion:1},key())).rejects.toMatchObject({code:'INVALID_STATE'});await store.reset(SEEDED.operator,SEEDED.buyer,{confirmation:'RESET STAGING SUBJECT',expectedVersion:1},key());const creatorReset=await store.reset(SEEDED.operator,SEEDED.creator,{confirmation:'RESET STAGING SUBJECT',expectedVersion:1},key());expect(creatorReset.body.newBalance).toMatchObject({available:'0.00',reserved:'0.00',total:'0.00'});await expect(store.reset(SEEDED.operator,SEEDED.operator,{confirmation:'RESET STAGING SUBJECT',expectedVersion:1},key())).rejects.toMatchObject({code:'FORBIDDEN'});expect(await store.ledgerConservation()).toBe(0n);await db.close();});

  it('keeps staging routes physically absent from the production application',async()=>{const config=loadConfig({NODE_ENV:'production',PUBLIC_ORIGIN:'https://cloud.kai.com',AUDIT_PEPPER:'a'.repeat(32),CURSOR_SECRET:'c'.repeat(32),PII_ENCRYPTION_KEY:Buffer.alloc(32,4).toString('base64'),DATABASE_URL:'postgres://isolated/staging',KAI_OIDC_SUBJECT_PEPPER:'s'.repeat(32),KAI_RESOURCE_ACCESS_TOKEN_FORMAT:'opaque'});const app=await buildApp({config,database:null,logger:false});expect((await app.inject({method:'GET',url:'/mobile/v1/staging/catalog'})).statusCode).toBe(404);expect((await app.inject({method:'POST',url:'/staging/v1/operator/test-subjects/x/reset'})).statusCode).toBe(404);await app.close();});

  it('writes only explicitly marked staging simulation records and seeds funding once',{timeout:30_000},async()=>{const{db,store}=await fixture();await store.initialize(tokens);const tables=(await db.query<{tablename:string}>(`SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename LIKE 'sandbox_%'`)).rows.map(row=>row.tablename);expect(tables.length).toBeGreaterThan(10);for(const table of tables){const unsafe=(await db.query<{count:string}>(`SELECT count(*)::text AS count FROM ${table} WHERE NOT simulation OR environment<>'staging'`)).rows[0]!.count;expect(unsafe,table).toBe('0');}expect((await db.query<{count:string}>(`SELECT count(*)::text AS count FROM sandbox_accounts WHERE subject_id IS NULL AND kind='demo_funding'`)).rows[0]!.count).toBe('1');await db.close();});
});
