import { Ionicons } from '@expo/vector-icons';
import { useVideoPlayer, VideoView } from 'expo-video';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { CloudPaySnapshot } from '../api';
import { ApiError } from '../api-client';
import { createVideoTask, getVideoTask, type VideoTask } from '../video-generation';
import { colors } from '../theme';

type Props = Readonly<{ snapshot: CloudPaySnapshot; onLogin: () => void }>;
function GeneratedVideo({ uri }: Readonly<{ uri: string }>) { const player = useVideoPlayer(uri, (instance) => { instance.loop = true; instance.play(); }); return <VideoView player={player} style={styles.video} nativeControls contentFit="contain" />; }
const statusLabels: Record<VideoTask['status'], string> = { queued: '已进入生成队列', in_progress: 'AI 正在生成', succeeded: '生成完成', failed: '生成失败' };

export function VideoGenerationScreen({ snapshot, onLogin }: Props) {
  const [prompt, setPrompt] = useState('KAI 在未来算力宇宙中穿越云海，镜头震撼推进，电影级 3D 光影');
  const [task, setTask] = useState<VideoTask | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!task || task.status === 'succeeded' || task.status === 'failed') return; let cancelled = false; const poll = async () => { try { const result = await getVideoTask(task.taskId); if (!cancelled) { setTask(result.task); setError(null); } } catch (reason) { if (!cancelled) setError(reason instanceof ApiError ? reason.message : '查询生成状态失败，请稍后重试。'); } }; const timer = setInterval(() => void poll(), 3000); return () => { cancelled = true; clearInterval(timer); }; }, [task]);
  const submit = async () => { if (!snapshot.authenticated) { onLogin(); return; } const clean = prompt.trim(); if (clean.length < 3) { setError('请至少输入 3 个字的视频描述。'); return; } setBusy(true); setError(null); setTask(null); try { setTask((await createVideoTask(clean)).task); } catch (reason) { setError(reason instanceof ApiError ? reason.message : '视频任务创建失败，请稍后重试。'); } finally { setBusy(false); } };
  return <View style={styles.root}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.hero}><View style={styles.kicker}><Ionicons name="sparkles" size={16} color="#8BD8FF" /><Text style={styles.kickerText}>KAI MOTION LAB</Text></View><Text style={styles.title}>让 KAI 动起来</Text><Text style={styles.subtitle}>用一句话生成电影感 3D 视频，生成任务和结果链接只归属于当前账号。</Text></View>{!snapshot.authenticated ? <View style={styles.card}><Ionicons name="lock-closed-outline" size={28} color={colors.primary} /><Text style={styles.cardTitle}>登录后使用 Seedance</Text><Text style={styles.cardText}>生成任务和视频记录会按账号隔离保存。</Text><Pressable onPress={onLogin} style={styles.primary}><Text style={styles.primaryText}>登录 Zod</Text></Pressable></View> : <><View style={styles.card}><Text style={styles.label}>视频描述</Text><TextInput value={prompt} onChangeText={setPrompt} multiline maxLength={2000} placeholder="描述角色、镜头、风格和动作…" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.counter}>{prompt.length}/2000</Text><Pressable disabled={busy} onPress={() => void submit()} style={[styles.primary, busy && styles.disabled]}>{busy ? <ActivityIndicator color={colors.surface} /> : <><Ionicons name="flash" size={17} color={colors.surface} /><Text style={styles.primaryText}>生成 KAI 视频</Text></>}</Pressable></View>{task ? <View style={styles.card}><View style={styles.statusRow}><View style={[styles.statusDot, task.status === 'succeeded' && styles.doneDot, task.status === 'failed' && styles.failDot]} /><Text style={styles.status}>{statusLabels[task.status]}</Text>{task.status !== 'succeeded' && task.status !== 'failed' ? <ActivityIndicator size="small" color={colors.primary} /> : null}</View><Text style={styles.taskPrompt} numberOfLines={3}>{task.prompt}</Text>{task.status === 'succeeded' && task.videoUrl ? <GeneratedVideo uri={task.videoUrl} /> : null}{task.status === 'failed' ? <Text style={styles.errorText}>{task.errorMessage ?? '生成失败，请修改描述后重试。'}</Text> : null}</View> : null}</>}{error ? <View style={styles.errorBanner}><Ionicons name="alert-circle-outline" size={18} color="#B42318" /><Text style={styles.errorText}>{error}</Text></View> : null}</ScrollView></View>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.canvas }, content: { padding: 16, paddingBottom: 32, gap: 14 }, hero: { padding: 20, borderRadius: 18, backgroundColor: '#07182D' }, kicker: { flexDirection: 'row', alignItems: 'center', gap: 7 }, kickerText: { color: '#8BD8FF', fontSize: 10, fontWeight: '900', letterSpacing: 1.5 }, title: { color: '#FFFFFF', fontSize: 30, fontWeight: '900', marginTop: 16 }, subtitle: { color: '#B9C9DC', fontSize: 12, lineHeight: 19, marginTop: 8 }, card: { padding: 16, borderRadius: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line }, cardTitle: { color: colors.ink, fontSize: 16, fontWeight: '900', marginTop: 9 }, cardText: { color: colors.muted, fontSize: 11, textAlign: 'center', marginTop: 7 }, label: { color: colors.ink, fontSize: 12, fontWeight: '900' }, input: { minHeight: 112, marginTop: 10, padding: 12, borderRadius: 10, color: colors.ink, backgroundColor: '#F6F8FA', fontSize: 13, lineHeight: 20, textAlignVertical: 'top' }, counter: { color: colors.muted, fontSize: 10, textAlign: 'right', marginTop: 5 }, primary: { minHeight: 46, marginTop: 13, paddingHorizontal: 16, borderRadius: 10, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, backgroundColor: colors.primary }, primaryText: { color: colors.surface, fontSize: 13, fontWeight: '900' }, disabled: { opacity: 0.6 }, statusRow: { flexDirection: 'row', alignItems: 'center', gap: 8 }, statusDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: '#F59E0B' }, doneDot: { backgroundColor: '#20A162' }, failDot: { backgroundColor: '#D92D20' }, status: { flex: 1, color: colors.ink, fontSize: 13, fontWeight: '900' }, taskPrompt: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 12 }, video: { width: '100%', aspectRatio: 16 / 9, marginTop: 14, borderRadius: 10, backgroundColor: '#06101F' }, errorBanner: { padding: 13, borderRadius: 10, flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: '#FEF3F2' }, errorText: { flex: 1, color: '#B42318', fontSize: 11, lineHeight: 17 }, });
