import type {FastifyInstance,FastifyRequest} from 'fastify';import{z}from'zod';import type{AccountService}from'../account/service.js';import{AppError}from'../errors.js';import type{DeviceCommerceService}from'./service.js';
import { authenticateMobileRequest } from '../account/request-auth.js';
function parse<T>(s:z.ZodType<T>,v:unknown){const r=s.safeParse(v);if(!r.success)throw new AppError('VALIDATION_ERROR',400,'提交的信息不完整或格式不正确。');return r.data;}function ctx(r:FastifyRequest){return{requestId:r.id,ip:r.ip};}function key(r:FastifyRequest){return String(r.headers['idempotency-key']??'');}
export async function registerDeviceCommerceRoutes(app:FastifyInstance,accounts:AccountService,devices:DeviceCommerceService){
 app.get('/mobile/v1/device-products',async r=>{const session=r.headers.authorization||r.headers['x-kai-id-token']?await authenticateMobileRequest(accounts,r):null;return{ok:true,products:await devices.products(session?.principal)}});
 app.get('/mobile/v1/device-products/:productId',async r=>{const session=r.headers.authorization||r.headers['x-kai-id-token']?await authenticateMobileRequest(accounts,r):null;const p=parse(z.object({productId:z.string().uuid()}),r.params);return{ok:true,product:await devices.product(session?.principal,p.productId)}});
 app.post('/mobile/v1/device-orders',async(r,reply)=>{const{principal}=await authenticateMobileRequest(accounts, r);const b=parse(z.object({productId:z.string().uuid(),quantity:z.number().int().min(1).max(20),shippingAddressReference:z.string().min(8).max(160)}).strict(),r.body);const x=await devices.create(principal,{...b,idempotencyKey:key(r)},ctx(r));return reply.status(x.replayed?200:201).send({ok:true,...x})});
 app.get('/mobile/v1/device-orders',async r=>{const{principal}=await authenticateMobileRequest(accounts, r);return{ok:true,orders:await devices.orders(principal)}});
 app.get('/mobile/v1/device-orders/:orderId',async r=>{const{principal}=await authenticateMobileRequest(accounts, r);const p=parse(z.object({orderId:z.string().uuid()}),r.params);return{ok:true,order:await devices.get(principal,p.orderId)}});
 app.get('/mobile/v1/device-assets',async r=>{const{principal}=await authenticateMobileRequest(accounts, r);return{ok:true,assets:await devices.assets(principal)}});
 app.post('/mobile/v1/device-orders/:orderId/cancel',async r=>{const{principal}=await authenticateMobileRequest(accounts, r);const p=parse(z.object({orderId:z.string().uuid()}),r.params);return{ok:true,...await devices.cancel(principal,p.orderId,key(r),ctx(r))}});
 app.post('/mobile/v1/provider/device-orders/:orderId/confirm',async r=>{const{principal}=await authenticateMobileRequest(accounts, r);const p=parse(z.object({orderId:z.string().uuid()}),r.params);return{ok:true,...await devices.confirm(principal,p.orderId,key(r),ctx(r))}});
 app.post('/mobile/v1/provider/device-orders/:orderId/ship',async r=>{const{principal}=await authenticateMobileRequest(accounts, r);const p=parse(z.object({orderId:z.string().uuid()}),r.params);const b=parse(z.object({logisticsProvider:z.string().trim().min(2).max(80),trackingNumber:z.string().trim().min(6).max(80).regex(/^[A-Za-z0-9-]+$/u)}).strict(),r.body);return{ok:true,...await devices.ship(principal,p.orderId,key(r),ctx(r),b)}});
 app.post('/mobile/v1/device-orders/:orderId/receive',async r=>{const{principal}=await authenticateMobileRequest(accounts, r);const p=parse(z.object({orderId:z.string().uuid()}),r.params);return{ok:true,...await devices.receive(principal,p.orderId,key(r),ctx(r))}});
 app.get('/mobile/v1/operator/device-products/:productId/activation-readiness',async r=>{const{principal}=await authenticateMobileRequest(accounts, r);const p=parse(z.object({productId:z.string().uuid()}),r.params);const q=parse(z.object({supplierSubjectId:z.string().uuid()}).strict(),r.query);return{ok:true,...await devices.activationReadiness(principal,p.productId,q.supplierSubjectId)}});
 app.put('/mobile/v1/operator/device-products/:productId/activate',async r=>{const{principal}=await authenticateMobileRequest(accounts, r);const p=parse(z.object({productId:z.string().uuid()}),r.params);const b=parse(z.object({supplierSubjectId:z.string().uuid()}).strict(),r.body);return{ok:true,product:await devices.activate(principal,p.productId,b.supplierSubjectId)}});
}
